export const siteConfig = {
  author: 'Inori',
  title: 'Inori Blog',
  description: 'Inori Blog generated by issues',
  lang: 'zh-CN',
}

export const navLinks = [
  {
    title: 'Blog',
    path: '/posts',
    icon: 'i-icon-park-outline-align-text-right-one',
  },
  {
    title: 'Projects',
    path: '/projects',
    icon: 'i-icon-park-outline-blocks-and-arrows',
  },
  {
    title: 'Tags',
    path: '/tags',
    icon: 'i-icon-park-outline-tag-one',
  },
  {
    title: 'About',
    path: '/',
    icon: 'i-icon-park-outline-grinning-face-with-open-mouth',
  },

]


